### ISSUE TITLE
Any chance of getting this included in github/pages-gem?

### ISSUE THREAD

**Issue by qwtel** [benbalter/jekyll-include-cache#18]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

Difficulty creating a template that works in environments that don't support `include_cached`, i.e. GitHub Pages.

### Describe the solution you'd like

Is there any chance of getting this included in [github/pages-gem](https://github.com/github/pages-gem)?

### Describe alternatives you've considered

* Running `sed -i '' 's/include_cached/include/g'` on my entire template and shipping 2 versions...
* Trying to get this included in Jekyll itself!?

### Additional context

n/a

**Comment by benbalter** [comment]
It is! https://github.com/github/pages-gem/blob/master/lib/github-pages/plugins.rb#L39

<blockquote><img src="https://avatars3.githubusercontent.com/u/9919?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/github/pages-gem">github/pages-gem</a></strong></div><div>A simple Ruby Gem to bootstrap dependencies for setting up and maintaining a local Jekyll environment in sync with GitHub Pages - github/pages-gem</div></blockquote>

**Comment by qwtel** [comment]
Oh, that's good news. 

FYI: It's missing from the [the GitHub Pages Dependency versions page](https://pages.github.com/versions/).

**Comment by benbalter** [comment]
> FYI: It's missing from the the GitHub Pages Dependency versions page.

Given the complexity and potential support burden, we added it, so that advanced users like yourself could use it, but it's a bit of a "need to know" feature, to prevent less experienced users from breaking their site when trying to optimize their build (without the ability to debug what's going on).
