### ISSUE TITLE
bad {page.url}

### ISSUE THREAD

**Issue by julienguegan** [benbalter/jekyll-include-cache#23]
### Describe the bug

The liquid variable `{page.url}` is broken when using it ina file which is called with `include_cached`. It does not give the correct **page.url**

### Steps to reproduce the behavior

1. call `page.url` in any html
2. call `page.url` but in a html called with `include_cached`
3. both are different : the one use with `include_cached` is incorrect

### Expected behavior

When using `include_cached` the correct value for `page.url` should be returned

### Others
- jekyll 4.2.1
- jekyll-include-cache 0.2.1
- theme mmistakes/minimal-mistakes 4.24.0

**Comment by benbalter** [comment]
@julienguegan per [the README](https://github.com/benbalter/jekyll-include-cache#one-potential-gotcha):

> For Jekyll Include Cache to work, you cannot rely on the page context to pass variables to your include (e.g., `assign foo=bar` or `page.title`). Instead, you must explicitly pass all variables to the include as arguments, and reference them within the include as `include.foo` (instead of `page.foo` or just `foo`).

Is that differing from the behavior you are observing?

**Comment by julienguegan** [comment]
you're absolutely right ! My bad ... And thank you 👍 I close the issue right away !
